### ISSUE TITLE
Klipper API socket not located in folder indicated by read.me

### ISSUE THREAD

**Issue by Ahartry** [unjordy/klipper-repl#4]
I am trying to get this to work, but the path specified by the read.me for the API socket location is not correct (I have no /run/klipper folder). Looking online, I am unable to find anything at all regarding where the API is located. Is it possible for additional info be added to the instructions regarding finding the API, or for some way to detect its location be added?

**Comment by unjordy** [comment]
The readme links to [the Klipper docs](https://www.klipper3d.org/API_Server.html) which are the best source for this — specifically, passing the option `-a <path>` to `klippy.py` will open a socket at `<path>`. `/run/klipper` is the default that NixOS uses for the socket, but it can be anywhere. Unfortunately I don’t think there’s any programmatic way to determine the socket path since it’s a runtime flag, and I don’t know if there’s a default socket path for MainsailOS or KIAUH because I don’t use Klipper on a Raspberry Pi.

**Comment by Ahartry** [comment]
Thanks for responding so fast. I was able to locate the path in the moonraker.cfg file via the mainsail UI. For anyone else who needs it, the API path is specified by the fourth line, which looks like this:

klippy_uds_address: /home/server/printer_data/comms/klippy.sock

With this I now have it working.
